name: Manual Assume Role and List S3 Buckets

on:
  workflow_dispatch:

jobs:
  assume-role-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure base credentials (IAM user)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "✅ Base credentials configured."
          echo aws configure list

      - name: Assume role manually and export credentials
        id: assume
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          ROLE_ARN="arn:aws:iam::557690577575:role/terraform-role"
          SESSION_NAME="gterraform-user-role"
          EXTERNAL_ID="terraform-user"  # optional if your trust policy requires it

          CREDS=$(aws sts assume-role \
            --role-arn "$ROLE_ARN" \
            --role-session-name "$SESSION_NAME" \
            --duration-seconds 900 \
            --output json)

          echo "Exporting temporary credentials..."
          echo "AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDS | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV

      - name: Verify assumed role identity
        run: aws sts get-caller-identity

      - name: List S3 buckets with assumed role
        run: aws s3 ls
