name: Terraform Run Scripts

on:
  workflow_dispatch:

jobs:
  assume-role-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_version: 1.8.0

      - name: Configure base credentials (IAM user)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "✅ Base credentials configured."

      - name: Prepare Terraform directory
        run: |
          mkdir -p Terraform/run
          cp -r Terraform/modules/vpc/* Terraform/run/
          cp Terraform/modules/global-override.tfvars Terraform/run/

      - name: Terraform Init and Plan with tfvars
        working-directory: Terraform/run
        run: |
          terraform init --reconfigure
          terraform plan -var-file="global-override.tfvars" -out=tfplan
