name: Terraform Run Scripts

on:
  workflow_dispatch:

jobs:
  assume-role-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure base credentials (IAM user)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "✅ Base credentials configured."

      - name: doing terraform init
        run: cd terraform/module/vpc && terraform init  
